### PR TITLE
Add config file for alioth global (POCO F3)

### PR DESCRIPTION
**Pull request by d-e-n-n-i-s-t**
stock MIUI global fingerprint (V14.0.4.0.TKHMIXM)
unfortunately I did not find any newer fingerprints for stock MIUI global. This should be new enough, as it's the newest android version

### CODE REVIEW

**Comment by althafvly** [comment]
Does it pass device integrity?

**Comment by giner** [comment]
@althafvly which app do you use to check this? Experiments show that SafetyNet Test + YASNAC + "Play Protection certification" passing do not guarantee Wallet to work.

**Comment by althafvly** [comment]
@giner it should pass atleast basic and device integrity in this app
https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck

**Comment by d-e-n-n-i-s-t** [comment]
@althafvly I honestly don't know if it passes device integrity, didn't check. I always thought device integrity has the same requirements for all fingerprints/devices, but just found out that spoofing is easier if you use an old fingerprint, so it's very well possible that this doesn't work.
I use my phone as daily driver so I don't want to experiment on it, guess we'll never know

**Pull request closed without merging**
